areas_reactivos:
    resource: "@AreasBundle/Resources/config/routing/reactivos.yml"
    prefix:   /reactivos

areas_subarea:
    resource: "@AreasBundle/Resources/config/routing/subarea.yml"
    prefix:   /subarea

areas_area:
    resource: "@AreasBundle/Resources/config/routing/area.yml"
    prefix:   /area

AreasBundle_perfil:
        resource: "@AreasBundle/Resources/config/routing/perfil.yml"
        prefix:   /perfil

