AreasBundle\Entity\SubArea:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombre:
            type: string
            length: 255
    manyToOne:
        Area:
            targetEntity: Area
            joinColumn:
                name: area_id
                referencedColumnName: id
                onDelete: CASCADE
    lifecycleCallbacks: {  }
