security:
    encoders:
        UsuarioBundle\Entity\Usuario: 
            algorithm: bcrypt
        Symfony\Component\Security\Core\User\User: #plaintext
            algorithm: bcrypt
            cost: 7

    role_hierarchy:
        ROLE_USER:          ROLE_USER
        ROLE_ADMIN:         ROLE_ADMIN
        ROLE_SUPER_ADMIN:   [ROLE_ALLOWED_TO_SWITCH, ROLE_USER,ROLE_ADMIN]

    providers:
        chain_provider:
            chain:
                providers: [in_memory, Usuario]
        in_memory:
            memory:
                users:
                    # NOTA: UNA VEZ PUESTO EL PROYECTO EN PRODUCCION, NO SE DEBE CAMBIAR NINGUNO DE LOS VALORES SIGUIENTES:
                    developer:
                        password: $2a$07$m2L.9HVxC0Y0bSzFTK5DoeXyQOTRfhPk6uyox2gvGIktpCRmYph9m
                        #dev
                        roles: 'ROLE_ADMIN'
        Usuario:
            entity:
                class: UsuarioBundle:Usuario
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        login:
            pattern: ^/login$
            security: false

        login_firewall:
            pattern: ^/login$
            anonymous: ~

        secured_area:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login_check
                always_use_default_target_path: true
                default_target_path: /index
            logout:
                path: /logout
                target: /login
            remember_me:
                key: holysoymuyseguro
                lifetime: 601800

        main:
            http_basic: ~
            stateless: true

        default:
            pattern: ^/
            http_basic: ~
            provider: Usuario
            #anonymous: ~
    access_control:
    # NOTA: LAS RESTRICCIONES DE ACCESO TAMBIÉN ESTÁN DECLARADAS EN LOS CONTROLADORES
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/index/new/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/index/create/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/index/*, roles: [ROLE_USER,ROLE_ADMIN] }
    - { path: ^/area/*, roles: [ROLE_ADMIN] }
    - { path: ^/preguntas/*, roles: [ROLE_ADMIN] }
    - { path: ^/subarea/*, roles: [ROLE_ADMIN] }
    - { path: ^/reactivos/*, roles: [ROLE_ADMIN] }
    - { path: ^/perfil/*, roles: [ROLE_ADMIN] }
