test_preguntas:
    resource: "@testBundle/Resources/config/routing/preguntas.yml"
    prefix:   /preguntas

test_setrespuestas:
    resource: "@testBundle/Resources/config/routing/setrespuestas.yml"
    prefix:   /setrespuestas

test_areascompletadas:
    resource: "@testBundle/Resources/config/routing/areascompletadas.yml"
    prefix:   /areascompletadas

test_opciones:
    resource: "@testBundle/Resources/config/routing/opciones.yml"
    prefix:   /opciones

test_test:
    resource: "@testBundle/Resources/config/routing/test.yml"
    prefix:   /test

test_homepage:
    path:     /hello/{name}
    defaults: { _controller: testBundle:Default:index }
test_resultados:
    path:     /{id}/resultados
    defaults: { _controller: testBundle:SetRespuestas:index }
test_realizados:
    path:     /realizados
    defaults: { _controller: testBundle:Test:realizados }
test_seguir:
    path:     /{id}/continuar
    defaults: { _controller: testBundle:Test:keepTest }
test_pdf:
    path:     /{id}/pdf
    defaults: { _controller: testBundle:SetRespuestas:renderPdf }
