testBundle\Entity\SetRespuestas:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        opcion:
            targetEntity: Opciones
            joinColumn:
                name: opciones_id
                referencedColumnName: id
                onDelete: CASCADE
        test:
            targetEntity: Test
            joinColumn:
                name: test_id
                referencedColumnName: id
                onDelete: CASCADE
    lifecycleCallbacks: {  }
